#ifndef __THREAD_ERROR_H__
#define __THREAD_ERROR_H__

// General
#define SUCCESS 0

// Allocator
#define ERROR_ALLOCATOR_INIT_FAILED -1
#define ERROR_ALLOCATOR_ADD_BLOCK_FAILED -2

// Thread
#define ERROR_THREADS_ALREADY_JOINED -1
#define ERROR_THREADS_COULD_NOT_FIND_BY_ID -2

#endif